title: Luc Cappellaro's blog
description: Keep calm and continue!
author: Luc Cappellaro

theme: minima
github_username:   LucCappellaro
linkedin_username: cappellaro
show_excerpts: true
google_analytics: true

disqus:
  shortname: utterances

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md

